In [87]:
import pandas as pd

In [88]:
df = pd.read_csv("plagiarism-msaladin-w1-msaladin-w2.csv")
df['plagiarism_score'] = pd.to_numeric(df['plagiarism_score'],errors='coerce')
df['ngram_length'] = pd.to_numeric(df['ngram_length'],errors='coerce')

In [89]:
df.head(5)

,token,plagiarism_score,context,ngram_length,language_model
0,de,1.000000,<s> de projectielantaarn,2.0,MLE
1,projectielantaarn,0.013605,de projectielantaarn aladin,2.0,MLE
2,aladin,0.500000,<s> de projectielantaarn aladin margaridas,2.0,MLE
3,margaridas,0.000000,de projectielantaarn aladin margaridas ante,2.0,MLE
4,ante,0.000000,projectielantaarn aladin margaridas ante porcos,2.0,MLE

In [90]:
df['quantile'] = pd.qcut(df['plagiarism_score'], [0, .25, .5, .75, 1], labels=False, duplicates="drop")

In [91]:
df.to_csv('quantiles-analysis.csv', index=False)

In [92]:
nonexact_n10 = df.loc[(df['plagiarism_score'] < 1.0) & (df['plagiarism_score'] >= 0.75) & (df['ngram_length'] == 10.0)]
nonexact_n9 = df.loc[(df['plagiarism_score'] < 1.0) & (df['plagiarism_score'] >= 0.75) & (df['ngram_length'] == 9.0)]
nonexact_n8 = df.loc[(df['plagiarism_score'] < 1.0) & (df['plagiarism_score'] >= 0.75) & (df['ngram_length'] == 8.0)]
nonexact_n7 = df.loc[(df['plagiarism_score'] < 1.0) & (df['plagiarism_score'] >= 0.75) & (df['ngram_length'] == 7.0)]
nonexact_n6 = df.loc[(df['plagiarism_score'] < 1.0) & (df['plagiarism_score'] >= 0.75) & (df['ngram_length'] == 6.0)]
nonexact_n5 = df.loc[(df['plagiarism_score'] < 1.0) & (df['plagiarism_score'] >= 0.75) & (df['ngram_length'] == 5.0)]
nonexact_n4 = df.loc[(df['plagiarism_score'] < 1.0) & (df['plagiarism_score'] >= 0.75) & (df['ngram_length'] == 4.0)]
nonexact_n3 = df.loc[(df['plagiarism_score'] < 1.0) & (df['plagiarism_score'] >= 0.75) & (df['ngram_length'] == 3.0)]
nonexact_n2 = df.loc[(df['plagiarism_score'] < 1.0) & (df['plagiarism_score'] >= 0.75) & (df['ngram_length'] == 2.0)]

In [93]:
nonexact_n10_a = df.loc[(df['plagiarism_score'] < 0.75) & (df['plagiarism_score'] >= 0.5) & (df['ngram_length'] == 10.0)]
nonexact_n9_a = df.loc[(df['plagiarism_score'] < 0.75) & (df['plagiarism_score'] >= 0.5) & (df['ngram_length'] == 9.0)]
nonexact_n8_a = df.loc[(df['plagiarism_score'] < 0.75) & (df['plagiarism_score'] >= 0.5) & (df['ngram_length'] == 8.0)]
nonexact_n7_a = df.loc[(df['plagiarism_score'] < 0.75) & (df['plagiarism_score'] >= 0.5) & (df['ngram_length'] == 7.0)]
nonexact_n6_a = df.loc[(df['plagiarism_score'] < 0.75) & (df['plagiarism_score'] >= 0.5) & (df['ngram_length'] == 6.0)]
nonexact_n5_a = df.loc[(df['plagiarism_score'] < 0.75) & (df['plagiarism_score'] >= 0.5) & (df['ngram_length'] == 5.0)]
nonexact_n4_a = df.loc[(df['plagiarism_score'] < 0.75) & (df['plagiarism_score'] >= 0.5) & (df['ngram_length'] == 4.0)]
nonexact_n3_a = df.loc[(df['plagiarism_score'] < 0.75) & (df['plagiarism_score'] >= 0.5) & (df['ngram_length'] == 3.0)]
nonexact_n2_a = df.loc[(df['plagiarism_score'] < 0.75) & (df['plagiarism_score'] >= 0.5) & (df['ngram_length'] == 2.0)]

In [94]:
nonexact_n10_b = df.loc[(df['plagiarism_score'] < 0.5) & (df['plagiarism_score'] >= 0.25) & (df['ngram_length'] == 10.0)]
nonexact_n9_b = df.loc[(df['plagiarism_score'] < 0.5) & (df['plagiarism_score'] >= 0.25) & (df['ngram_length'] == 9.0)]
nonexact_n8_b = df.loc[(df['plagiarism_score'] < 0.5) & (df['plagiarism_score'] >= 0.25) & (df['ngram_length'] == 8.0)]
nonexact_n7_b = df.loc[(df['plagiarism_score'] < 0.5) & (df['plagiarism_score'] >= 0.25) & (df['ngram_length'] == 7.0)]
nonexact_n6_b = df.loc[(df['plagiarism_score'] < 0.5) & (df['plagiarism_score'] >= 0.25) & (df['ngram_length'] == 6.0)]
nonexact_n5_b = df.loc[(df['plagiarism_score'] < 0.5) & (df['plagiarism_score'] >= 0.25) & (df['ngram_length'] == 5.0)]
nonexact_n4_b = df.loc[(df['plagiarism_score'] < 0.5) & (df['plagiarism_score'] >= 0.25) & (df['ngram_length'] == 4.0)]
nonexact_n3_b = df.loc[(df['plagiarism_score'] < 0.5) & (df['plagiarism_score'] >= 0.25) & (df['ngram_length'] == 3.0)]
nonexact_n2_b = df.loc[(df['plagiarism_score'] < 0.5) & (df['plagiarism_score'] >= 0.25) & (df['ngram_length'] == 2.0)]

In [95]:
nonexact_n10_c = df.loc[(df['plagiarism_score'] < 0.25) & (df['plagiarism_score'] >= 0.0) & (df['ngram_length'] == 10.0)]
nonexact_n9_c = df.loc[(df['plagiarism_score'] < 0.25) & (df['plagiarism_score'] >= 0.0) & (df['ngram_length'] == 9.0)]
nonexact_n8_c = df.loc[(df['plagiarism_score'] < 0.25) & (df['plagiarism_score'] >= 0.0) & (df['ngram_length'] == 8.0)]
nonexact_n7_c = df.loc[(df['plagiarism_score'] < 0.25) & (df['plagiarism_score'] >= 0.0) & (df['ngram_length'] == 7.0)]
nonexact_n6_c = df.loc[(df['plagiarism_score'] < 0.25) & (df['plagiarism_score'] >= 0.0) & (df['ngram_length'] == 6.0)]
nonexact_n5_c = df.loc[(df['plagiarism_score'] < 0.25) & (df['plagiarism_score'] >= 0.0) & (df['ngram_length'] == 5.0)]
nonexact_n4_c = df.loc[(df['plagiarism_score'] < 0.25) & (df['plagiarism_score'] >= 0.0) & (df['ngram_length'] == 4.0)]
nonexact_n3_c = df.loc[(df['plagiarism_score'] < 0.25) & (df['plagiarism_score'] >= 0.0) & (df['ngram_length'] == 3.0)]
nonexact_n2_c = df.loc[(df['plagiarism_score'] < 0.25) & (df['plagiarism_score'] >= 0.0) & (df['ngram_length'] == 2.0)]

In [96]:
nonexact_n4.head(5)

,token,plagiarism_score,context,ngram_length,language_model,quantile
38080,elegant,0.875039,aladin margaridas ante porcos een mooie vrouwe...,4.0,Witten-Bell,1.0
38084,van,0.757205,een mooie vrouwenhand elegant niettegenstaande...,4.0,Witten-Bell,1.0
38085,het,0.776284,mooie vrouwenhand elegant niettegenstaande de ...,4.0,Witten-Bell,1.0
38087,manipuleert,0.875039,elegant niettegenstaande de vergrooting van he...,4.0,Witten-Bell,1.0
38088,een,0.878370,niettegenstaande de vergrooting van het closeu...,4.0,Witten-Bell,1.0

In [97]:
nonexact_n4_a.head(5)

,token,plagiarism_score,context,ngram_length,language_model,quantile
7087,afgerolde,0.5,bioscoop apollo aan den operateur die de afger...,4.0,MLE,0.0
7143,niets,0.5,dergelijke geestdrift is er in de zaal niets te,4.0,MLE,0.0
7340,greta,0.5,even voorstellen ik ben de materialisatie van ...,4.0,MLE,0.0
7401,de,0.5,film maar ik ben de materialisatie van de heldin,4.0,MLE,0.0
7691,bij,0.5,hotel te willen uitzien ik kan u bij voorbeeld,4.0,MLE,0.0

In [98]:
nonexact_n4_b.head(5)

,token,plagiarism_score,context,ngram_length,language_model,quantile
7342,a,0.333333,ik ben de materialisatie van greta brenn a u,4.0,MLE,0.0
7634,zich,0.333333,factoren het astraal ik van greta brenn zich v...,4.0,MLE,0.0
7843,wel,0.333333,permitteert de directeurhij zich af en toe wel...,4.0,MLE,0.0
8193,van,0.333333,t is u meteen verwittigen dat er van de,4.0,MLE,0.0
9727,een,0.333333,ik ga het publiek verwittigen dat er een defect,4.0,MLE,0.0

In [99]:
nonexact_n4_c.head(5)

,token,plagiarism_score,context,ngram_length,language_model,quantile
6923,projectielantaarn,0.0,<s> <s> de projectielantaarn aladin,4.0,MLE,0.0
6924,aladin,0.0,<s> de projectielantaarn aladin margaridas,4.0,MLE,0.0
6925,margaridas,0.0,de projectielantaarn aladin margaridas ante,4.0,MLE,0.0
6926,ante,0.0,<s> <s> <s> de projectielantaarn aladin margar...,4.0,MLE,0.0
6927,porcos,0.0,<s> <s> de projectielantaarn aladin margaridas...,4.0,MLE,0.0

In [100]:
nonexact_n4.to_csv('upper_quantile_fourgram.csv', index=False)
nonexact_n4_a.to_csv('midupper_quantile_fourgram.csv', index=False)
nonexact_n4_b.to_csv('midlower_quantile_fourgram.csv', index=False)
nonexact_n4_c.to_csv('lower_quantile_fourgram.csv', index=False)

In [ ]:
# train on everything else
# fasttext in gensim?
# no stemming or lemmatization, no stopwords removal
# push to Github